// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: proto/hello/hello.proto

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hello_SayHello_FullMethodName       = "/hello.Hello/SayHello"
	Hello_StreamReplies_FullMethodName  = "/hello.Hello/StreamReplies"
	Hello_StreamRequests_FullMethodName = "/hello.Hello/StreamRequests"
)

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务：service
type HelloClient interface {
	// 方法1:单项 RPC(一次请求对应一次响应)
	SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error)
	// 方法2：服务端流式RPC（一次请求，多次响应：流式响应）
	StreamReplies(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelloRes], error)
	// 客户端流式 RPC
	StreamRequests(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloReq, HelloRes], error)
}

type helloClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloClient(cc grpc.ClientConnInterface) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloRes)
	err := c.cc.Invoke(ctx, Hello_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) StreamReplies(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelloRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Hello_ServiceDesc.Streams[0], Hello_StreamReplies_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloReq, HelloRes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hello_StreamRepliesClient = grpc.ServerStreamingClient[HelloRes]

func (c *helloClient) StreamRequests(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloReq, HelloRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Hello_ServiceDesc.Streams[1], Hello_StreamRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloReq, HelloRes]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hello_StreamRequestsClient = grpc.ClientStreamingClient[HelloReq, HelloRes]

// HelloServer is the server API for Hello service.
// All implementations must embed UnimplementedHelloServer
// for forward compatibility.
//
// 定义服务：service
type HelloServer interface {
	// 方法1:单项 RPC(一次请求对应一次响应)
	SayHello(context.Context, *HelloReq) (*HelloRes, error)
	// 方法2：服务端流式RPC（一次请求，多次响应：流式响应）
	StreamReplies(*HelloReq, grpc.ServerStreamingServer[HelloRes]) error
	// 客户端流式 RPC
	StreamRequests(grpc.ClientStreamingServer[HelloReq, HelloRes]) error
	mustEmbedUnimplementedHelloServer()
}

// UnimplementedHelloServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelloServer struct{}

func (UnimplementedHelloServer) SayHello(context.Context, *HelloReq) (*HelloRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHelloServer) StreamReplies(*HelloReq, grpc.ServerStreamingServer[HelloRes]) error {
	return status.Error(codes.Unimplemented, "method StreamReplies not implemented")
}
func (UnimplementedHelloServer) StreamRequests(grpc.ClientStreamingServer[HelloReq, HelloRes]) error {
	return status.Error(codes.Unimplemented, "method StreamRequests not implemented")
}
func (UnimplementedHelloServer) mustEmbedUnimplementedHelloServer() {}
func (UnimplementedHelloServer) testEmbeddedByValue()               {}

// UnsafeHelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloServer will
// result in compilation errors.
type UnsafeHelloServer interface {
	mustEmbedUnimplementedHelloServer()
}

func RegisterHelloServer(s grpc.ServiceRegistrar, srv HelloServer) {
	// If the following call panics, it indicates UnimplementedHelloServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hello_ServiceDesc, srv)
}

func _Hello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hello_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_StreamReplies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloServer).StreamReplies(m, &grpc.GenericServerStream[HelloReq, HelloRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hello_StreamRepliesServer = grpc.ServerStreamingServer[HelloRes]

func _Hello_StreamRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServer).StreamRequests(&grpc.GenericServerStream[HelloReq, HelloRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hello_StreamRequestsServer = grpc.ClientStreamingServer[HelloReq, HelloRes]

// Hello_ServiceDesc is the grpc.ServiceDesc for Hello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hello_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamReplies",
			Handler:       _Hello_StreamReplies_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamRequests",
			Handler:       _Hello_StreamRequests_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/hello/hello.proto",
}
