syntax = "proto3";  //指定 proto 版本：3

package hello;  //包名

option go_package = "go-grpc/go-grpc-server/proto/hello;hello"; //指明go对应包名

//定义服务：service
service Hello {
    //方法1:单项 RPC(一次请求对应一次响应)
    rpc SayHello(HelloReq) returns(HelloRes){}

    //方法2：服务端流式RPC（一次请求，多次响应：流式响应）
    rpc StreamReplies(HelloReq) returns(stream HelloRes){}

    // 客户端流式 RPC
    rpc StreamRequests (stream HelloReq) returns (HelloRes) {}

    //todo：其他RPC待实现
}

//HelloReq 请求结构体
message HelloReq {
    string request = 1; //从1开始，顺序增加
    int32 id = 2;
    string email = 3;

}

//HelloRes 响应结构体
message HelloRes {
    string responce = 1 ;
    int64 timestamp = 2;
}