// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/hello/hello.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HelloReq 请求结构体
type HelloReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"` //从1开始，顺序增加
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	mi := &file_proto_hello_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *HelloReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HelloReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// HelloRes 响应结构体
type HelloRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responce      string                 `protobuf:"bytes,1,opt,name=responce,proto3" json:"responce,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRes) Reset() {
	*x = HelloRes{}
	mi := &file_proto_hello_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRes) ProtoMessage() {}

func (x *HelloRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRes.ProtoReflect.Descriptor instead.
func (*HelloRes) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRes) GetResponce() string {
	if x != nil {
		return x.Responce
	}
	return ""
}

func (x *HelloRes) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_hello_hello_proto protoreflect.FileDescriptor

const file_proto_hello_hello_proto_rawDesc = "" +
	"\n" +
	"\x17proto/hello/hello.proto\x12\x05hello\"J\n" +
	"\bHelloReq\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"D\n" +
	"\bHelloRes\x12\x1a\n" +
	"\bresponce\x18\x01 \x01(\tR\bresponce\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\xa6\x01\n" +
	"\x05Hello\x12.\n" +
	"\bSayHello\x12\x0f.hello.HelloReq\x1a\x0f.hello.HelloRes\"\x00\x125\n" +
	"\rStreamReplies\x12\x0f.hello.HelloReq\x1a\x0f.hello.HelloRes\"\x000\x01\x126\n" +
	"\x0eStreamRequests\x12\x0f.hello.HelloReq\x1a\x0f.hello.HelloRes\"\x00(\x01B*Z(go-grpc/go-grpc-server/proto/hello;hellob\x06proto3"

var (
	file_proto_hello_hello_proto_rawDescOnce sync.Once
	file_proto_hello_hello_proto_rawDescData []byte
)

func file_proto_hello_hello_proto_rawDescGZIP() []byte {
	file_proto_hello_hello_proto_rawDescOnce.Do(func() {
		file_proto_hello_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hello_hello_proto_rawDesc), len(file_proto_hello_hello_proto_rawDesc)))
	})
	return file_proto_hello_hello_proto_rawDescData
}

var file_proto_hello_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_hello_hello_proto_goTypes = []any{
	(*HelloReq)(nil), // 0: hello.HelloReq
	(*HelloRes)(nil), // 1: hello.HelloRes
}
var file_proto_hello_hello_proto_depIdxs = []int32{
	0, // 0: hello.Hello.SayHello:input_type -> hello.HelloReq
	0, // 1: hello.Hello.StreamReplies:input_type -> hello.HelloReq
	0, // 2: hello.Hello.StreamRequests:input_type -> hello.HelloReq
	1, // 3: hello.Hello.SayHello:output_type -> hello.HelloRes
	1, // 4: hello.Hello.StreamReplies:output_type -> hello.HelloRes
	1, // 5: hello.Hello.StreamRequests:output_type -> hello.HelloRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_hello_hello_proto_init() }
func file_proto_hello_hello_proto_init() {
	if File_proto_hello_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hello_hello_proto_rawDesc), len(file_proto_hello_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hello_hello_proto_goTypes,
		DependencyIndexes: file_proto_hello_hello_proto_depIdxs,
		MessageInfos:      file_proto_hello_hello_proto_msgTypes,
	}.Build()
	File_proto_hello_hello_proto = out.File
	file_proto_hello_hello_proto_goTypes = nil
	file_proto_hello_hello_proto_depIdxs = nil
}
